### ISSUE TITLE
Add helper for deploying static assets and compressed files to S3 

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-ci-shared-helpers#21]
In order to correctly upload the compressed assets generated by apps using Page kit we need to update our deployment process.

Currently we use the [`deploy-hashed-assets` command of nht](https://github.com/Financial-Times/n-heroku-tools/blob/master/tasks/deploy-hashed-assets.js) as `n-ui` apps did previously, however we noted that this tool is only required to handle the specific output from `n-ui`. Therefore, updating a tool which is no longer required, and has nothing to do with Heroku, to handle these assets does not make sense.

Instead we propose using a relatively simple [bash script](https://gist.github.com/quarterto/4e8bbb7391455d15dbe40be74150dcd3) which uses the AWS CLI. This should be included in this repo to be made available to our CI environment.

Once this is done we should require only a small change to `n-gage` in order to enable it.

---

## To-do:

- [ ] Add install of AWS CLI to Circle config (https://circleci.com/docs/2.0/deployment-integrations/#aws)
- [ ] Add upload script to CI shared helpers (https://gist.github.com/quarterto/4e8bbb7391455d15dbe40be74150dcd3)
- [ ] Refactor `n-gage` to use new upload script (https://github.com/Financial-Times/n-gage/blob/master/src/tasks/deploy.mk#L2-L9)

**Comment by i-like-robots** [comment]
@quarterto @CLTPayne Is this a reasonable summary?
